apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: budgeting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: brendanhunter/budgeting-app-backend:latest
        imagePullPolicy: Always
        env:
        - name: TYPEORM_CONNECTION
          value: "postgres"
        - name: TYPEORM_HOST
          value: "postgres"
        - name: TYPEORM_PORT
          value: "5432"
        - name: TYPEORM_USERNAME
          value: "user"
        - name: TYPEORM_PASSWORD
          value: "password"
        - name: TYPEORM_DATABASE
          value: "budgeting_app"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: budgeting-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
